// TruthScore extension — shared i18n (English default, any language).
// Mirrors Dashboard.html's I18N approach. LANG is detected from the browser
// (navigator.language) and overridable via chrome.storage.sync ("lang"),
// persisted in localStorage for synchronous first paint.
//
// Loaded before popup.js in popup.html. Exposes globals: t(), TS_LANG,
// tsApplyI18n(), tsSetLang(), TS_TOPIC_LABELS.
const TS_I18N = {
  en: {
    tagline: 'AI Fact Checker',
    tabVerify: '🔍 Verify', tabAI: '🤖 AI Detect', tabHistory: '📋 History',
    verify: 'Verify', verifying: 'Searching evidence…',
    fromPage: '📋 From page', scanPage: '🔍 Scan page',
    claimPlaceholder: 'Enter a claim or a paragraph. Each fact is verified separately…',
    emptyVerifyTitle: 'No active check', emptyVerifyDesc: 'Enter a claim or select text<br>on any web page.',
    verdictCorrect: 'Is this verdict correct?', yes: '👍 Yes', no: '👎 No',
    aiPlaceholder: 'Paste the text you want to analyze…\n\nWorks for English and Romanian text.\nAt least 50 characters.',
    detectAI: '🤖 Detect AI', analyzing: 'Analyzing text…',
    emptyAITitle: 'AI Content Detector', emptyAIDesc: 'Detect whether a text was<br>generated by ChatGPT / GPT-4 / Claude.',
    probAI: '🤖 AI prob.', probHuman: '✍️ Human prob.',
    wordsPerSent: 'Words/sent.', vocab: 'Vocab', sentences: 'Sentences',
    histTitleN: 'Last {n} checks', histLatest: 'Latest checks', clearHist: '🗑 Clear',
    histEmpty: 'No checks in history', reverify: 'Re-verify', confirmClear: 'Clear all history?',
    now: 'now',
    login: 'Log in', register: 'Register', logout: 'Log out',
    authTitle: 'Sign in', regTitle: 'New free account',
    email: 'Email', password: 'Password', name: 'Name', yourName: 'Your name',
    yourPassword: 'Your password', passMin: 'At least 6 characters',
    loginBtn: 'Sign in →', registerBtn: 'Create free account →',
    orSep: 'or', continueGoogle: 'Continue with Google',
    noAccount: 'No account?', signUp: 'Sign up', haveAccount: 'Already have an account?', signIn: 'Sign in',
    upgrade: '⭐ Upgrade', openDashboard: 'Open dashboard', logoutTitle: 'Log out',
    footerInfo: '🔬 40+ sources · 26 domains', settings: 'Settings →',
    unlimitedNoBanner: '⚡ Unlimited checks, no banner', proArrow: 'Pro →', quotaLeft: 'Checks left today: {n}',
    usageToday: '{used}/{limit} today', bonusEarned: '+1 bonus check! 🎁',
    // runtime / errors
    enterClaim: 'Enter a claim.', selectFirst: 'Select text on the page first.',
    noPageAccess: 'Could not access the page.', backendOffline: 'Backend offline',
    fillAll: 'Fill in all fields', genericError: 'Error', unknownError: 'Unknown error.',
    min20: 'Enter at least 20 characters.', noText: 'Could not extract text.',
    connectingGoogle: '⏳ Connecting with Google…', googleTokenMissing: 'Google token not found',
    googleAuthError: 'Google Auth error',
    // verify steps
    stepClassify: 'Classifying the domain…', stepSearch: 'Searching evidence…',
    stepCompare: 'Analyzing and comparing evidence…', stepScore: 'Computing TruthScore…',
    // verdict labels
    TRUE: 'TRUE', FALSE: 'FALSE', UNCERTAIN: 'UNCERTAIN', MIXED: 'MIXED', MIXEDlong: 'MIXED (partly true)',
    confHigh: '🟢 High', confMed: '🟡 Medium', confLow: '🔴 Low',
    evidence: 'evidence', supportN: 'support', contradictN: 'contradict', relevantN: 'relevant',
    sourcesTitle: 'Sources & Evidence', grpSupport: '✅ Supports', grpContradict: '❌ Contradicts', grpRelevant: '⚪ Relevant',
    subClaims: 'Sub-claims',
    perClaimResult: 'Result per claim ({n})', tapClaim: 'Tap a claim for its full analysis.',
    claimSources: '📎 SOURCES · CLAIM #{n}', noDirectEvidence: 'no direct evidence', otherSources: '+{n} more sources', sourceFallback: 'source',
    paraSplit: 'The text was split and verified per claim.',
    riskHigh: '🔴 High risk', riskMed: '🟡 Medium risk', riskLow: '🟢 Low risk',
    likelyAI: '🤖 Likely AI', likelyHuman: '✍️ Likely human', aiUncertain: '❓ Uncertain',
    // content script (in-page panel + scan)
    ctxReload: 'Extension reloaded — reload the page (F5).',
    ctxInvalidated: 'Extension context invalidated — reload the page.',
    scanDetecting: '🔍 Detecting verifiable claims…',
    scanNoText: 'Not enough text found.', scanBackendOffline: '❌ Backend offline.',
    scanNoClaims: 'No verifiable claims detected.',
    scanVerifying: 'verifying…', scanDone: 'Done', scanClaims: 'claims',
    verifyingShort: '⏳ Verifying…', clickDetails: 'Click for details',
    clearHighlights: '🗑 Clear highlights', analyzing: 'Analyzing…',
    loadStep1: 'Searching 17 sources…', loadStep2: 'Running embeddings…',
    loadStep3: 'Applying NLI…', loadStep4: 'Computing TruthScore…',
    backendHint: 'Backend offline. Run: uvicorn main:app --reload',
    claimSourcesPara: '📎 SOURCES FOR CLAIM #{n}', claimsWord: 'claims',
    analysisCorrect: 'Is this analysis correct?',
    fbThanks: '👍 Thanks!', fbNoted: '👎 Noted, we\'ll improve.',
    sponsorLine: '⚡ <b>TruthScore Pro</b> — unlimited checks, no ad',
    // options page
    optTitle: 'Settings', optSubtitle: 'API configuration',
    optLangCard: '🌐 Language', optLangLabel: 'Interface language',
    optLangHelp: 'Applies to the popup, in-page panel and dashboard.',
    optRequired: 'required', optFree: 'free',
    optBackendCard: '🐍 Python backend', optBackendUrl: 'FastAPI backend URL',
    optBackendHelp: 'Run the backend:', optTestBtn: '🔌 Test connection',
    optHfLabel: 'HF Token (set in backend .env)', optSetInEnv: 'Set in truthscore-backend/.env',
    optHfHelp1: 'Model:', optHfHelp2: 'Get a free token:',
    optGcCard: '🔎 Google Fact Check', optGcLabel: 'Google API Key (set in backend .env)',
    optGcHelp: 'Enable the Fact Check Tools API in:',
    optSaveBtn: '💾 Save', optSaved: '✅ Saved successfully!',
    optTesting: '⏳ Testing connection…', optOnline: '✅ Backend online! Model: {model}',
    optConnFail: '❌ Could not connect. Check that the backend is running.',
  },
  ro: {
    tagline: 'AI Fact Checker',
    tabVerify: '🔍 Verifică', tabAI: '🤖 AI Detect', tabHistory: '📋 Istoric',
    verify: 'Verifică', verifying: 'Se caută dovezi…',
    fromPage: '📋 Din pagină', scanPage: '🔍 Scan pagină',
    claimPlaceholder: 'Introdu o afirmație sau un paragraf. Fiecare fapt va fi verificat separat…',
    emptyVerifyTitle: 'Nicio verificare activă', emptyVerifyDesc: 'Introdu o afirmație sau selectează text<br>pe orice pagină web.',
    verdictCorrect: 'Verdictul e corect?', yes: '👍 Da', no: '👎 Nu',
    aiPlaceholder: 'Lipește textul pe care vrei să îl analizezi…\n\nFuncționează pentru texte în română și engleză.\nMinim 50 de caractere.',
    detectAI: '🤖 Detectează AI', analyzing: 'Se analizează textul…',
    emptyAITitle: 'AI Content Detector', emptyAIDesc: 'Detectează dacă un text a fost<br>generat de ChatGPT / GPT-4 / Claude.',
    probAI: '🤖 Prob. AI', probHuman: '✍️ Prob. uman',
    wordsPerSent: 'Cuv/prop.', vocab: 'Vocab', sentences: 'Propoziții',
    histTitleN: 'Ultimele {n} verificări', histLatest: 'Ultimele verificări', clearHist: '🗑 Șterge',
    histEmpty: 'Nicio verificare în istoric', reverify: 'Re-verifică', confirmClear: 'Ștergi tot istoricul?',
    now: 'acum',
    login: 'Autentificare', register: 'Înregistrează-te', logout: 'Deconectare',
    authTitle: 'Autentificare', regTitle: 'Cont nou gratuit',
    email: 'Email', password: 'Parolă', name: 'Nume', yourName: 'Numele tău',
    yourPassword: 'Parola ta', passMin: 'Minim 6 caractere',
    loginBtn: 'Autentifică-te →', registerBtn: 'Creează cont gratuit →',
    orSep: 'sau', continueGoogle: 'Continuă cu Google',
    noAccount: 'Nu ai cont?', signUp: 'Înregistrează-te', haveAccount: 'Ai deja cont?', signIn: 'Autentifică-te',
    upgrade: '⭐ Upgrade', openDashboard: 'Deschide dashboard', logoutTitle: 'Deconectare',
    footerInfo: '🔬 40+ surse · 26 domenii', settings: 'Configurare →',
    unlimitedNoBanner: '⚡ Verificări nelimitate, fără acest banner', proArrow: 'Pro →', quotaLeft: 'Verificări rămase azi: {n}',
    usageToday: '{used}/{limit} azi', bonusEarned: '+1 verificare bonus! 🎁',
    enterClaim: 'Introdu o afirmație.', selectFirst: 'Selectează mai întâi text pe pagină.',
    noPageAccess: 'Nu s-a putut accesa pagina.', backendOffline: 'Backend offline',
    fillAll: 'Completează toate câmpurile', genericError: 'Eroare', unknownError: 'Eroare necunoscută.',
    min20: 'Introdu cel puțin 20 de caractere.', noText: 'Nu s-a putut extrage text.',
    connectingGoogle: '⏳ Se conectează cu Google…', googleTokenMissing: 'Token Google negăsit',
    googleAuthError: 'Eroare Google Auth',
    stepClassify: 'Se clasifică domeniul…', stepSearch: 'Se caută dovezi…',
    stepCompare: 'Se analizează și se compară dovezile…', stepScore: 'Se calculează TruthScore…',
    TRUE: 'ADEVĂRAT', FALSE: 'FALS', UNCERTAIN: 'INCERT', MIXED: 'MIXT', MIXEDlong: 'MIXT (parțial adevărat)',
    confHigh: '🟢 Ridicată', confMed: '🟡 Medie', confLow: '🔴 Scăzută',
    evidence: 'dovezi', supportN: 'susțin', contradictN: 'contrazic', relevantN: 'relevante',
    sourcesTitle: 'Surse & Evidențe', grpSupport: '✅ Susțin', grpContradict: '❌ Contrazic', grpRelevant: '⚪ Relevante',
    subClaims: 'Sub-afirmații',
    perClaimResult: 'Rezultat pe fiecare afirmație ({n})', tapClaim: 'Apasă pe o afirmație pentru analiza ei completă.',
    claimSources: '📎 SURSE · AFIRMAȚIA #{n}', noDirectEvidence: 'fără dovezi directe', otherSources: '+{n} alte surse', sourceFallback: 'sursă',
    paraSplit: 'Textul a fost împărțit și verificat pe afirmații.',
    riskHigh: '🔴 Risc ridicat', riskMed: '🟡 Risc mediu', riskLow: '🟢 Risc scăzut',
    likelyAI: '🤖 Probabil AI', likelyHuman: '✍️ Probabil om', aiUncertain: '❓ Incert',
    // content script (in-page panel + scan)
    ctxReload: 'Extensie reîncărcată — reîncarcă pagina (F5).',
    ctxInvalidated: 'Context extensie invalidat — reîncarcă pagina.',
    scanDetecting: '🔍 Se detectează afirmații verificabile…',
    scanNoText: 'Nu s-a găsit text suficient.', scanBackendOffline: '❌ Backend offline.',
    scanNoClaims: 'Nicio afirmație verificabilă detectată.',
    scanVerifying: 'în verificare…', scanDone: 'Complet', scanClaims: 'afirmații',
    verifyingShort: '⏳ Se verifică…', clickDetails: 'Click pentru detalii',
    clearHighlights: '🗑 Șterge highlights', analyzing: 'Se analizează…',
    loadStep1: 'Se caută în 17 surse…', loadStep2: 'Se rulează embeddings…',
    loadStep3: 'Se aplică NLI…', loadStep4: 'Se calculează TruthScore…',
    backendHint: 'Backend offline. Rulează: uvicorn main:app --reload',
    claimSourcesPara: '📎 SURSE PENTRU AFIRMAȚIA #{n}', claimsWord: 'afirmații',
    analysisCorrect: 'Analiza e corectă?',
    fbThanks: '👍 Mulțumim!', fbNoted: '👎 Notat, vom îmbunătăți.',
    sponsorLine: '⚡ <b>TruthScore Pro</b> — verificări nelimitate, fără acest anunț',
    // options page
    optTitle: 'Configurare', optSubtitle: 'Configurare API',
    optLangCard: '🌐 Limbă', optLangLabel: 'Limba interfeței',
    optLangHelp: 'Se aplică în popup, panoul din pagină și dashboard.',
    optRequired: 'necesar', optFree: 'gratis',
    optBackendCard: '🐍 Backend Python', optBackendUrl: 'URL Backend FastAPI',
    optBackendHelp: 'Rulează backendul:', optTestBtn: '🔌 Test conexiune',
    optHfLabel: 'HF Token (setat în .env pe backend)', optSetInEnv: 'Setat în truthscore-backend/.env',
    optHfHelp1: 'Model:', optHfHelp2: 'Obține token gratuit:',
    optGcCard: '🔎 Google Fact Check', optGcLabel: 'Google API Key (setat în .env pe backend)',
    optGcHelp: 'Activează Fact Check Tools API în:',
    optSaveBtn: '💾 Salvează', optSaved: '✅ Salvat cu succes!',
    optTesting: '⏳ Se testează conexiunea…', optOnline: '✅ Backend online! Model: {model}',
    optConnFail: '❌ Nu s-a putut conecta. Verifică dacă backendul rulează.',
  },
};

const TS_TOPIC_LABELS_I18N = {
  en: { medical:'Medicine',biology:'Biology',chemistry:'Chemistry',physics:'Physics',astronomy:'Astronomy',mathematics:'Mathematics',logic:'Logic',cs_tech:'Computer Science',engineering:'Engineering',geography:'Geography',history:'History',literature:'Literature',art:'Art',sports:'Sports',economics:'Economics',business:'Business',climate:'Climate',politics:'Politics',sociology:'Sociology',psychology:'Psychology',philosophy:'Philosophy',ethics:'Ethics',religion:'Religion',nutrition:'Nutrition',news:'News',general:'General' },
  ro: { medical:'Medicină',biology:'Biologie',chemistry:'Chimie',physics:'Fizică',astronomy:'Astronomie',mathematics:'Matematică',logic:'Logică',cs_tech:'Informatică',engineering:'Inginerie',geography:'Geografie',history:'Istorie',literature:'Literatură',art:'Artă',sports:'Sport',economics:'Economie',business:'Business',climate:'Climă',politics:'Politică',sociology:'Sociologie',psychology:'Psihologie',philosophy:'Filosofie',ethics:'Etică',religion:'Religie',nutrition:'Nutriție',news:'Știri',general:'General' },
};

let TS_LANG = (localStorage.getItem('ts_lang') || (navigator.language || 'en').slice(0, 2).toLowerCase());
if (!TS_I18N[TS_LANG]) TS_LANG = 'en';

// t('key', {n: 5}) — returns the active-language string, {n} interpolated.
function t(key, vars) {
  let s = (TS_I18N[TS_LANG] && TS_I18N[TS_LANG][key]) || TS_I18N.en[key] || key;
  if (vars) for (const k in vars) s = s.replace('{' + k + '}', vars[k]);
  return s;
}
const TS_TOPIC_LABELS = new Proxy({}, {
  get: (_t, k) => (TS_TOPIC_LABELS_I18N[TS_LANG] || TS_TOPIC_LABELS_I18N.en)[k],
});

function tsSetLang(l) {
  if (!TS_I18N[l]) l = 'en';
  TS_LANG = l;
  localStorage.setItem('ts_lang', l);
  try { chrome.storage.sync.set({ lang: l }); } catch (e) {}
  tsApplyI18n();
}

// Apply to static markup: data-i18n (textContent), data-i18n-html (innerHTML),
// data-i18n-ph (placeholder), data-i18n-title (title attribute).
function tsApplyI18n() {
  document.documentElement.lang = TS_LANG;
  document.querySelectorAll('[data-i18n]').forEach(el => { el.textContent = t(el.getAttribute('data-i18n')); });
  document.querySelectorAll('[data-i18n-html]').forEach(el => { el.innerHTML = t(el.getAttribute('data-i18n-html')); });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => { el.setAttribute('placeholder', t(el.getAttribute('data-i18n-ph'))); });
  document.querySelectorAll('[data-i18n-title]').forEach(el => { el.setAttribute('title', t(el.getAttribute('data-i18n-title'))); });
}

// Sync language from chrome.storage.sync (set on the options page or dashboard)
// before first paint, then apply.
(async () => {
  try {
    const { lang } = await chrome.storage.sync.get('lang');
    if (lang && TS_I18N[lang] && lang !== TS_LANG) {
      TS_LANG = lang;
      localStorage.setItem('ts_lang', lang);
    }
  } catch (e) {}
  if (document.readyState !== 'loading') tsApplyI18n();
  else document.addEventListener('DOMContentLoaded', tsApplyI18n);
})();
